version: '3.8'

services:
  grpc:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfile.multi
    container_name: library
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - tom:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-qwerty}

volumes:
  tom: