# syntax=docker/dockerfile:1

FROM golang:latest

EXPOSE 8080

WORKDIR /library-app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY ./ ./

RUN go build -o ./bin/server cmd/server/*.go
RUN go build -o ./bin/client cmd/client/*.go

CMD ["./bin/server"]